company_name_code = {
    'ADIN': 'Ading AD Skopje',
    'ALK': 'Alkaloid AD Skopje',
    'ALKB': 'Alkaloid AD Berovo',
    'AMBR': 'AM Broker AD Skopje',
    'AMEH': 'Agromehanika AD Skopje',
    'APTK': 'Angropromet Tikvesanka AD Kavadarci',
    'ATPP': 'ATP Proleter Kriva Palanka',
    'AUMK': 'Automakedonija AD Skopje',
    'BANA': 'Rudnici Banani AD Skopje',
    'BGOR': 'Kristal 1923 AD Veles',
    'BIKF': 'Tekstil Elma AD Prilep',
    'BIM': 'BIM AD Sveti Nikole',
    'BLTU': 'Blagoj Tufanov AD Radovis',
    'CBNG': 'Crveni bregovi Negotino',
    'CDHV': 'Centralen depozitar za hartii od vrednost AD Skopje',
    'CEVI': 'FZC 11 Oktomvri AD Kumanovo',
    'CKB': 'Centralna kooperativna banka AD Skopje',
    'CKBKO': 'Centralna kooperativna banka AD Skopje',
    'DEBA': 'Debarski bani - Capa AD Debar',
    'DIMI': 'Dimko Mitrev AD Veles',
    'EDST': 'Edinstvo Struga',
    'ELMA': 'Elmar Stip',
    'ELNC': 'Elenica Strumica',
    'ENER': 'Energomont Skopje',
    'ENSA': 'Fleks Broker AD Skopje',
    'EUHA': 'Eurohaus AD Skopje',
    'EUMK': 'Euromak broker AD Skopje',
    'EVRO': 'Evropa AD Skopje',
    'FAKM': 'Fakom AD Skopje',
    'FERS': 'Fersped AD Skopje',
    'FKTL': 'FK Struga-Trim-Lum AD Struga',
    'FROT': 'Frotirka kompani AD Delcevo',
    'FUBT': 'Fustelarko Borec AD Bitola',
    'GALE': 'Galeb Ohrid',
    'GDKM': 'ZIK Gradiste Kumanovo',
    'GECK': 'Geras Cunev Konfekcija AD Strumica',
    'GECT': 'Geras Cunev Trgovija AD Strumica',
    'GIMS': 'Gradezen institut Makedonija AD',
    'GRDN': 'Granit AD Skopje',
    'GRNT': 'Granit AD Skopje',
    'GRSN': 'Gradinar Sveti Nikole',
    'GRZD': 'Grozd AD Strumica',
    'GTC': 'GTC AD Skopje',
    'GTRG': 'Getro Gostivar',
    'IJUG': 'Institut za zavaruv. Jug Skopje',
    'INB': 'Sparkase banka AD Skopje',
    'INDI': 'Ineks Drim AD Struga',
    'INEK': 'Ineks AD Gorica Ohrid',
    'INHO': 'Internesnel Hotels AD Skopje',
    'INOV': 'Inovo Broker AD Skopje',
    'INPR': 'Interpromet AD Tetovo',
    'INTP': 'Kapital Banka AD Skopje',
    'JAKO': 'Javor Konsalting Bitola',
    'JULI': 'Palplast AD Kumanovo',
    'JUSK': 'Jugotutun Skopje',
    'KARO': 'Karaorman Skopje',
    'KDFO': 'NLB Fondovi AD Skopje',
    'KJUBI': 'Makedonija osiguruvane AD Skopje - Viena Insurens Grup',
    'KKFI': 'MKK Euronikel 2005 AD Kavadarci',
    'KKST': 'KK Strumica 2022 AD Strumica',
    'KLST': 'Klanica so ladilnik AD Strumica',
    'KMB': 'Komercijalna Banka AD Skopje',
    'KMPR': 'Komunaproekt Tetovo',
    'KOMU': 'DS Smith AD Skopje',
    'KONF': 'Konzervna fabrika Strumica',
    'KONZ': 'Fruktal Mak AD Skopje',
    'KORZ': 'Stokovna kuka KORZO AD Bitola',
    'KPSS': 'Fabrika Karpos AD Skopje',
    'KJUBI': 'Makedonija osiguruvane AD Skopje',
    'KULT': 'Kultura Skopje',
    'KVAS': 'Kvasara AD Bitola',
    'LAJO': 'Lajon Ins AD Skopje',
    'LHND': 'Lihnida Ohrid',
    'LOTO': 'Lotarija na Makedonija AD Skopje',
    'LOZP': 'Pelisterka AD Skopje',
    'MAGP': 'FK Makedonija Gjorrche Petrov - 1932 AD Skopje',
    'MAKP': 'Makpromet AD Stip',
    'MAKS': 'Makoteks AD Skopje',
    'MB': 'Makedonska Berza AD Skopje',
    'MERM': 'Mermeren kombinat AD Prilep',
    'MKSD': 'Makosped AD Skopje',
    'MLKR': 'Mlekara Bitola',
    'MODA': 'Moda AD Sveti Nikole',
    'MPOL': 'Hoteli-Metropol AD Ohrid',
    'MPT': 'Makpetrol AD Skopje',
    'MPTE': 'AD Makpetrol-Teas Skopje',
    'MTUR': 'Makedonijaturist AD Skopje',
    'MZHE': 'Vabtek MZT AD Skopje',
    'MZPU': 'MZT Pumpi AD Skopje',
    'NEME': 'Nemetali Ograzden AD Strumica',
    'NOSK': 'Nova stokovna kuka AD Strumica',
    'OBPP': 'Polisa plus Skopje',
    'OILK': 'OILKO KDA Skopje',
    'OKTA': 'OKTA AD Skopje',
    'OMOS': 'Vega osiguruvanje AD Skopje',
    'OPFO': 'Opfolio AD Skopje',
    'OPTK': 'Ocna optika Getaldus Skopje',
    'ORAN': 'Oranzerii Hamzali AD Strumica',
    'OSPO': 'Osiguritelna polisa AD Skopje',
    'OTEK': 'Oteks Ohrid',
    'PELK': 'Pelagonija komerc Bitola',
    'PGGV': 'Pelagonija Gostivar',
    'PKB': 'Pekabesko AD Kadino, Ilinden',
    'POPK': 'Popova kula AD Demir Kapija',
    'PPIV': 'Prilepska pivarnica AD Prilep',
    'PROD': 'OP Prosvetno Delo Skopje',
    'PROT': 'Protektor AD Prilep',
    'PTRS': 'Roman AD Prilep',
    'RADE': 'Rade Koncar - Aparatna tehnika AD Skopje',
    'REPL': 'Replek AD Skopje',
    'RIMI': 'RIMI AD Stip',
    'RINS': 'Reing AD Skopje',
    'RZEK': 'RZ Ekonomika AD Skopje',
    'RZIT': 'RZ Inter-Transsped AD Skopje',
    'RZIZ': 'RZ Inzinering Skopje',
    'RZLE': 'ArcelorMittal (HRM) AD Skopje',
    'RZLV': 'Liberti AD Skopje',
    'RZTK': 'RZ Tehnicka kontrola AD Skopje',
    'RZUG': 'Ugotur AD Skopje',
    'RZUS': 'RZ Uslugi AD Skopje',
    'SBT': 'Stopanska banka AD Bitola',
    'STB': 'Stopanska banka AD Skopje',
    'SDOM': 'Sovremen dom AD Prilep',
    'SIL': 'Sileks AD Kratovo',
    'SKON': 'Industrijal Struma AD Strumica',
    'SBT': 'Stopanska banka AD Bitola',
    'SKP': 'Skopski Pazar AD Skopje',
    'SLAV': 'Slavej AD Skopje',
    'SNBT': 'SN Osiguritelen broker AD Bitola',
    'STOK': 'Stokopromet AD Skopje',
    'SNBTO': 'SN Osiguritelen Broker AD Bitola',
    'SPOL': 'Strumicko pole AD s. Vasilevo',
    'SSPR': 'Sigurnosno staklo AD Prilep',
    'SPAZ': 'Skopski Pazar AD Skopje',
    'STIL': 'Makstil AD Skopje',
    'TIKV': 'GD Tikves AD Kavadarci',
    'TEL': 'Makedonski Telekom AD Skopje',
    'TKVS': 'VV Tikves AD Kavadarci',
    'TRDB': 'Trudbenik AD Ohrid',
    'TTK': 'TTK Banka AD Skopje',
    'TKPR': 'Tutunski kombinat AD Prilep',
    'TEAL': 'TEAL AD Tetovo',
    'TNB': 'NLB Banka AD Skopje',
    'TAJM': 'Tajmiste AD Kicevo',
    'TRPS': 'Patnicki soobrakaj - Transkop AD Bitola',
    'TETE': 'Teteks AD Tetovo',
    'TSMP': 'Trgotekstil maloprodazba AD Skopje',
    'TEHN': 'Tehnokomerc AD Skopje',
    'USJE': 'Cementarnica USJE AD Skopje',
    'UNI': 'UNI Banka AD Skopje',
    'VROS': 'Triglav osiguruvane AD Skopje',
    'VTKS': 'Veteks AD Veles',
    'VITA': 'Vitaminka AD Prilep',
    'ZAS': 'ZAS AD Skopje',
    'ZKAR': 'Zito Karaorman AD Kicevo',
    'ZILU': 'Zito Luks AD Skopje',
    'ZPOG': 'Zito Polog AD Tetovo',
    'ZPKO': 'ZK Pelagonija AD Bitola'
}