"""Added forecast_day column to Companies

Revision ID: a85abbbb9f81
Revises: 4669dc1c02ed
Create Date: 2024-12-27 00:00:19.677252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85abbbb9f81'
down_revision = '4669dc1c02ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_day', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('forecast_week', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('forecast_month', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.drop_column('forecast_month')
        batch_op.drop_column('forecast_week')
        batch_op.drop_column('forecast_day')

    # ### end Alembic commands ###
