"""Added recommendation column to Companies

Revision ID: f400755212c6
Revises: a85abbbb9f81
Create Date: 2024-12-29 18:14:35.831572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f400755212c6'
down_revision = 'a85abbbb9f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NLP_recommendation', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.drop_column('NLP_recommendation')

    # ### end Alembic commands ###
